flaskr/__init__.py
from flask import Flask, render_template
from config import Config

def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(Config)

    from flaskr.routes import view
    app.register_blueprint(view)

    return app

flaskr/routes.py
import sys, atexit, time
from flask import current_app as app
from flask import Blueprint, render_template, request, redirect, url_for

try:
    import RPi.GPIO as GPIO
except (RuntimeError, ModuleNotFoundError):
    import fake_rpi
    GPIO = fake_rpi.RPi.GPIO
    sys.modules['RPi'] = fake_rpi.RPi
    sys.modules['RPi.GPIO'] = fake_rpi.RPi.GPIO
    sys.modules['smbus'] = fake_rpi.smbus

view = Blueprint("view", __name__)

GPIO.setmode(GPIO.BOARD)
#pin 11
GPIO.setup(11,GPIO.OUT)
#pin 11, 50Hz pulse
servo = GPIO.PWM(11,50)
servo.start(0)
time.sleep(2)

values = {'0.00':0, '45.00':3, '90.00':6, '135.00':9, '180.00':12}

@view.route("/")
def homepage():
    return render_template("homepage.html")

@view.route("/update", methods=["POST"])
def update():
    sliderValue = request.form.get('sliderInput')
    dutyCycle = values[sliderValue]
    move(dutyCycle)
    return render_template("homepage.html", sliderValue = sliderValue)

def move(dutyCycle=3):
    servo.ChangeDutyCycle(dutyCycle)
    time.sleep(1)
    servo.ChangeDutyCycle(0)
    time.sleep(1)

def cleanUp():
    print('Safe terminating.')
    move()
    servo.stop
    GPIO.cleanup()

atexit.register(cleanUp)

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.svg') }}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
        
        <!-- DARK MODE -->
        <link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.css">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/servos_pi.css') }}">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/nouislider.css') }}">

        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap4.min.css"/>

        <title>Servos Pi</title>
    </head>

    <body>
        <script src="{{ url_for('static', filename='js/init.js') }}"></script>
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>


        <script src="{{ url_for('static', filename='js/nouislider.js') }}"></script>


        <nav class="navbar navbar-expand-lg navbar-dark">

            <a class="navbar-brand" href="{{ url_for('view.homepage') }}" data-toggle="tooltip" title="THPHat Pi">
                <div>
                    <div class="row">
                        <div class="col">
                            <img src="{{ url_for('static', filename='img/logo.svg') }}" class="logo">
                        </div>
                    </div>
                </div>
            </a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>            

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto"> 
                    <li class="nav-item active">
                        <a class="nav-item nav-link" href="{{ url_for('view.homepage') }}" title="Home">
                            Home
                        </a>
                    </li>

                </ul>
            </div>

        </nav>

        {% block content %}
        {% endblock %}

    </body>

</html>

flaskr/templates/homepage.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

  <div class="container content-container">
    <form method="POST" action="/update">
        <div class="form-group">

            <div>
                <input id="sliderInput" type="hidden" name="sliderInput" value="{{ sliderValue }}">                    
                <div id="slider"></div>
                <script>
                    createSlider('slider', 'sliderInput');
                </script>
            </div>

        </div>

        <button type="submit" class="btn btn-primary">Update</button>

    </form>
  </div>

{% endblock %}